<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="rufus">

  <!-- Constants -->
  <xacro:property name="chassis_length" value="0.6"/>
  <xacro:property name="chassis_width" value="0.4"/>
  <xacro:property name="chassis_height" value="0.15"/>
  <xacro:property name="chassis_mass" value="15.0"/>
  
  <xacro:property name="track_width" value="0.08"/>
  <xacro:property name="track_length" value="0.5"/>
  
  <xacro:property name="wheel_radius" value="0.05"/>
  <xacro:property name="wheel_width" value="0.04"/>
  <xacro:property name="wheel_mass" value="0.5"/>

  <!-- Colors -->
  <material name="black">
    <color rgba="0.1 0.1 0.1 1.0"/>
  </material>
  
  <material name="dark_blue">
    <color rgba="0.04 0.10 0.16 1.0"/>
  </material>
  
  <material name="gray">
    <color rgba="0.5 0.5 0.5 1.0"/>
  </material>

  <!-- Base Link -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="dark_blue"/>
    </visual>
    <collision>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${chassis_mass}"/>
      <inertia ixx="${chassis_mass/12*(chassis_width*chassis_width+chassis_height*chassis_height)}" 
               ixy="0.0" ixz="0.0"
               iyy="${chassis_mass/12*(chassis_length*chassis_length+chassis_height*chassis_height)}" 
               iyz="0.0"
               izz="${chassis_mass/12*(chassis_length*chassis_length+chassis_width*chassis_width)}"/>
    </inertial>
  </link>

  <!-- Base Footprint -->
  <link name="base_footprint"/>
  
  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
  </joint>

  <!-- Left Track -->
  <link name="left_track">
    <visual>
      <geometry>
        <box size="${track_length} ${track_width} 0.02"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <box size="${track_length} ${track_width} 0.02"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="2.0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
  </link>

  <joint name="left_track_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_track"/>
    <origin xyz="0 ${chassis_width/2+track_width/2} ${-chassis_height/2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- Right Track -->
  <link name="right_track">
    <visual>
      <geometry>
        <box size="${track_length} ${track_width} 0.02"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <box size="${track_length} ${track_width} 0.02"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="2.0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
  </link>

  <joint name="right_track_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_track"/>
    <origin xyz="0 ${-(chassis_width/2+track_width/2)} ${-chassis_height/2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- Arm Base Link -->
  <link name="arm_base_link">
    <visual>
      <geometry>
        <cylinder radius="0.05" length="0.08"/>
      </geometry>
      <material name="gray"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.05" length="0.08"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.5"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>
  </link>

  <joint name="arm_base_joint" type="fixed">
    <parent link="base_link"/>
    <child link="arm_base_link"/>
    <origin xyz="${chassis_length/4} 0 ${chassis_height/2+0.04}" rpy="0 0 0"/>
  </joint>

  <!-- Arm Link 1 (Base Rotation) -->
  <link name="arm_link_1">
    <visual>
      <geometry>
        <cylinder radius="0.04" length="0.15"/>
      </geometry>
      <material name="dark_blue"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.04" length="0.15"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.3"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.0005"/>
    </inertial>
  </link>

  <joint name="base_joint" type="revolute">
    <parent link="arm_base_link"/>
    <child link="arm_link_1"/>
    <origin xyz="0 0 0.115" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="${-pi}" upper="${pi}" effort="10.0" velocity="2.0"/>
  </joint>

  <!-- Arm Link 2 (Shoulder) -->
  <link name="arm_link_2">
    <visual>
      <origin xyz="0 0 0.1" rpy="0 0 0"/>
      <geometry>
        <box size="0.06 0.06 0.2"/>
      </geometry>
      <material name="gray"/>
    </visual>
    <collision>
      <origin xyz="0 0 0.1" rpy="0 0 0"/>
      <geometry>
        <box size="0.06 0.06 0.2"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.4"/>
      <inertia ixx="0.002" ixy="0.0" ixz="0.0" iyy="0.002" iyz="0.0" izz="0.0005"/>
    </inertial>
  </link>

  <joint name="shoulder_joint" type="revolute">
    <parent link="arm_link_1"/>
    <child link="arm_link_2"/>
    <origin xyz="0 0 0.075" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="${-pi/2}" upper="${pi/2}" effort="10.0" velocity="2.0"/>
  </joint>

  <!-- Arm Link 3 (Elbow) -->
  <link name="arm_link_3">
    <visual>
      <origin xyz="0 0 0.09" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.05 0.18"/>
      </geometry>
      <material name="dark_blue"/>
    </visual>
    <collision>
      <origin xyz="0 0 0.09" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.05 0.18"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.3"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.0003"/>
    </inertial>
  </link>

  <joint name="elbow_joint" type="revolute">
    <parent link="arm_link_2"/>
    <child link="arm_link_3"/>
    <origin xyz="0 0 0.2" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="${-pi/2}" upper="${pi/2}" effort="8.0" velocity="2.0"/>
  </joint>

  <!-- Arm Link 4 (Wrist Pitch) -->
  <link name="arm_link_4">
    <visual>
      <origin xyz="0 0 0.05" rpy="0 0 0"/>
      <geometry>
        <box size="0.04 0.04 0.1"/>
      </geometry>
      <material name="gray"/>
    </visual>
    <collision>
      <origin xyz="0 0 0.05" rpy="0 0 0"/>
      <geometry>
        <box size="0.04 0.04 0.1"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.2"/>
      <inertia ixx="0.0005" ixy="0.0" ixz="0.0" iyy="0.0005" iyz="0.0" izz="0.0002"/>
    </inertial>
  </link>

  <joint name="wrist_pitch_joint" type="revolute">
    <parent link="arm_link_3"/>
    <child link="arm_link_4"/>
    <origin xyz="0 0 0.18" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="${-pi/2}" upper="${pi/2}" effort="5.0" velocity="2.0"/>
  </joint>

  <!-- Arm Link 5 (Wrist Roll) -->
  <link name="arm_link_5">
    <visual>
      <geometry>
        <cylinder radius="0.02" length="0.06"/>
      </geometry>
      <material name="dark_blue"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.02" length="0.06"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.0002" ixy="0.0" ixz="0.0" iyy="0.0002" iyz="0.0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="wrist_roll_joint" type="revolute">
    <parent link="arm_link_4"/>
    <child link="arm_link_5"/>
    <origin xyz="0 0 0.1" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="${-pi}" upper="${pi}" effort="3.0" velocity="2.0"/>
  </joint>

  <!-- Gripper Base -->
  <link name="gripper_base">
    <visual>
      <geometry>
        <box size="0.04 0.06 0.03"/>
      </geometry>
      <material name="gray"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.04 0.06 0.03"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="gripper_joint" type="revolute">
    <parent link="arm_link_5"/>
    <child link="gripper_base"/>
    <origin xyz="0 0 0.045" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit lower="0" upper="${pi/4}" effort="2.0" velocity="1.0"/>
  </joint>

  <!-- Lidar -->
  <link name="lidar_link">
    <visual>
      <geometry>
        <cylinder radius="0.04" length="0.05"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.04" length="0.05"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.2"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="${chassis_length/2-0.05} 0 ${chassis_height/2+0.025}" rpy="0 0 0"/>
  </joint>

  <!-- Camera -->
  <link name="camera_link">
    <visual>
      <geometry>
        <box size="0.03 0.08 0.03"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.03 0.08 0.03"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
    </inertial>
  </link>

  <joint name="camera_joint" type="fixed">
    <parent link="base_link"/>
    <child link="camera_link"/>
    <origin xyz="${chassis_length/2-0.02} 0 ${chassis_height/2+0.05}" rpy="0 0 0"/>
  </joint>

  <!-- Gazebo-specific properties -->
  <gazebo reference="base_link">
    <material>Gazebo/DarkBlue</material>
  </gazebo>

  <gazebo reference="left_track">
    <material>Gazebo/Black</material>
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
  </gazebo>

  <gazebo reference="right_track">
    <material>Gazebo/Black</material>
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
  </gazebo>

</robot>

